# Generated by Django 6.1.2 on 2026-10-07 21:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ชื่อสินค้า')),
                ('category', models.CharField(choices=[('electronics', 'เครื่องใช้ไฟฟ้า / อิเล็กทรอนิกส์'), ('fashion', 'เสื้อผ้า / แฟชั่น'), ('furniture', 'เฟอร์นิเจอร์ / ของใช้ในบ้าน'), ('books', 'หนังสือ / การ์ตูน'), ('sports', 'กีฬา / จักรยาน'), ('other', 'อื่น ๆ')], default='other', max_length=20, verbose_name='หมวดหมู่')),
                ('condition', models.CharField(choices=[('like_new', 'เหมือนใหม่'), ('good', 'สภาพดี'), ('fair', 'พอใช้'), ('worn', 'มีตำหนิ')], default='good', max_length=20, verbose_name='สภาพสินค้า')),
                ('negotiable', models.BooleanField(default=False, verbose_name='ต่อรองราคาได้')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา (บาท)')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='รูปสินค้า')),
                ('status', models.CharField(choices=[('available', 'มีของ'), ('sold', 'ขายแล้ว')], default='available', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ลงขายเมื่อ')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขาย')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาที่ซื้อ')),
                ('address', models.TextField(verbose_name='ที่อยู่จัดส่ง')),
                ('status', models.CharField(choices=[('ordered', 'รอจัดส่ง'), ('shipped', 'จัดส่งแล้ว'), ('completed', 'สำเร็จ')], default='ordered', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สั่งซื้อเมื่อ')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ซื้อ')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='shop.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
    ]
