# Generated by Django 6.1.2 on 2026-10-08 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เริ่มคุยเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='ข้อความล่าสุดเมื่อ')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ซื้อ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='shop.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'ห้องแชท',
                'verbose_name_plural': 'ห้องแชท',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='ข้อความ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ส่งเมื่อ')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.conversation', verbose_name='ห้องแชท')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่ง')),
            ],
            options={
                'verbose_name': 'ข้อความ',
                'verbose_name_plural': 'ข้อความ',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('product', 'buyer'), name='unique_chat_per_buyer_product'),
        ),
    ]
